name: fluttertemplet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

analyzer:
#  enable-experiment:
#    - nullable
#  enable-experiment:
#    - non-nullable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
#  flutter_localizations:
#    sdk: flutter

#  splashscreen: ^1.3.5

  tuple: ^2.0.0

#  flutter_boost: ^1.17.1
  flutter_boost:
    git:
      url: 'git@github.com:alibaba/flutter_boost.git'
      ref: 'v3.0-null-safety-preview.13'

  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.7

#  flutter_local_notifications: ^5.0.0+4
  url_launcher: ^6.0.4

  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

#  logger: ^1.1.0
#  simple_logger: ^1.8.1+1

  textless: ^6.6.6
  division: ^0.8.8
  #  easy_localization:
#  flutter_hooks: ^
#  flutter_linkify: ^
  qr_flutter: ^3.2.0
  webview_flutter: ^2.0.8
  carousel_slider: ^4.0.0-nullsafety.0
  #    git:
  #      url: 'git@github.com:Fliggy-Mobile/fcommon.git'
  #      ref: 'master'
  flutter_staggered_grid_view: ^0.4.1

  permission_handler: ^7.2.0
  share: ^2.0.1
#  path_provider: ^2.0.1
  provider: ^6.0.1
  rxdart: ^0.27.3

#  shared_preferences: ^2.0.5

  get: ^4.1.4
  get_storage: ^2.0.2

#  cached_network_image: ^2.5.1
  hive: ^2.0.4

#  print_color: ^2.2.7
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
#  dio_http_cache: ^0.3.0
#  dio_http_cache:
#    git:
#    url: https://github.com/hurshi/dio-http-cache.git
  #引导图
#  tutorial_coach_mark: ^0.6.0+1
  popover: ^0.2.6+3

  styled_widget: ^0.3.1
  pull_to_refresh: ^1.6.5
  flutter_easyrefresh: 2.2.1

  auto_size_text: ^2.1.0
  table_calendar: ^2.3.3
  web_socket_channel: ^2.0.0
  timelines: ^0.1.0

  enhance_stepper: ^0.0.8
  enhance_expansion_panel: ^0.0.3
#  User:
#    hosted:
#      name: syn_mine_pages
#      url: git@github.com:shang1219178163/UserPlugin.git
#    version: 0.0.1

#  User: ^0.0.1
#    git:
#      url: 'git@github.com:shang1219178163/UserPlugin.git'
#      ref: 'master'

#  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
