name: flutter_templet_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

analyzer:
#  enable-experiment:
#    - nullablef
#  enable-experiment:
#    - non-nullable

environment:
  sdk: ">=2.12.0 <=3.10.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
#  flutter_localizations:
#    sdk: flutter

#  splashscreen: ^1.3.5
#  connectivity_plus: ^3.0.0
  connectivity: ^3.0.0
  tuple: ^2.0.0
  flutter_hooks: ^0.18.3
  flutter_screenutil: ^5.0.1
  cached_network_image: ^3.2.0
  video_player: ^2.2.3
#  chewie: ^1.4.0

  flutter_boost:
    git:
      url: 'git@github.com:alibaba/flutter_boost.git'
      ref: '4.2.1'

  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.7
  event_bus: ^2.0.0

#  flutter_local_notifications: ^5.0.0+4
  url_launcher: ^6.0.4

  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

  mime: ^1.0.3

  textless: ^6.6.6
  division: ^0.9.0
  #  easy_localization:
#  flutter_hooks: ^
#  flutter_linkify: ^
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  webview_flutter: ^2.0.8
  carousel_slider: 4.0.0
  #    git:
  #      url: 'git@github.com:Fliggy-Mobile/fcommon.git'
  #      ref: 'master'
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.18.0

  permission_handler: ^7.2.0
  share: ^2.0.1
#  path_provider: ^2.0.1
  provider: ^6.0.1
  rxdart: ^0.27.3

  shared_preferences: ^2.0.7
  #获取appName、packageName、version、buildNumber
  package_info_plus: ^1.4.2

  get: ^4.1.4
  get_storage: ^2.0.2

#  cached_network_image: ^2.5.1
  hive: ^2.0.4

#  print_color: ^2.2.7
  dio: ^5.1.0
  dio_cookie_manager: ^2.1.3
#  dio_http_cache: ^0.3.0
#  dio_http_cache:
#    git:
#    url: https://github.com/hurshi/dio-http-cache.git
  #引导图
#  tutorial_coach_mark: ^0.6.0+1
  popover: ^0.2.6+3

#  pull_to_refresh: ^1.6.5
  easy_refresh: ^3.3.1
  visibility_detector: ^0.3.3

  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  web_socket_channel: ^2.0.0

  font_awesome_flutter: ^9.0.0
  timelines: ^0.1.0

  enhance_stepper: ^0.1.1
  enhance_expansion_panel: ^0.0.3

  custom_timer: ^0.1.1
  scribble: ^0.9.0
  aesthetic_dialogs: ^0.0.15
  shimmer_animation: ^2.1.0+1
  image_gallery_saver: ^1.7.1

  flutter_swiper_null_safety: ^1.0.2
  flutter_smart_dialog: ^4.2.1
  flutter_rating_bar: ^4.0.0
  desktop_drop: ^0.4.1
  badges: ^2.0.3
  svgaplayer_flutter: ^2.0.0
#  flutter_svg: ^1.1.6
  sliver_tools: 0.2.7
  color_converter: ^0.2.1
  horizontal_data_table: ^4.1.4
  wechat_assets_picker: ^8.4.3
  dotted_border: ^2.0.0+3
  #  merge_images: ^1.0.3

  flutter_image_compress: ^1.1.3
  extended_image: ^7.0.2

  flutter_sound: ^9.2.13

  w_popup_menu: ^1.0.0

  azlistview: ^2.0.0
  common_utils: ^2.0.0
  lpinyin: ^2.0.0
  github_language_colors:
    git:
      url: git@github.com:Sky24n/github_language_colors.git

  syncfusion_flutter_datepicker: ^21.2.9

#  html: ^0.15.0
#  http: ^0.13.3
#  http: ^0.13.3
#  path_drawing: ^0.4.0
#  User:
#    hosted:
#      name: syn_mine_pages
#      url: git@github.com:shang1219178163/UserPlugin.git
#    version: 0.0.1

#  User: ^0.0.1
#    git:
#      url: 'git@github.com:shang1219178163/UserPlugin.git'
#      ref: 'master'

#  ansicolor: ^2.0.1

dependency_overrides:
#  scrollable_positioned_list: ^0.3.2
  scrollable_positioned_list: ^0.3.8

# User:
#   path: ../User

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

  build_runner: ^2.1.4


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
