name: flutter_templet_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+100
#自定义字段 - 项目别名
alias: flutter_templet


analyzer:
#  enable-experiment:
#    - nullablef
#  enable-experiment:
#    - non-nullable

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  cupertino_icons: ^1.0.3
  flutter_localizations:
    sdk: flutter


  yaml: ^3.1.2
  path: ^1.8.1
  package_config: ^2.1.0
  easy_localization: ^3.0.7+1

  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.1
#  splashscreen: ^1.3.5
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  dart_ping: ^9.0.1
  intl: ^0.19.0
  tuple: ^2.0.0
  event_bus: ^2.0.0
  flutter_hooks: ^0.21.2
  flutter_screenutil: ^5.0.1
  flutter_isolate: ^2.0.4
  cached_network_image: ^3.2.0

  scrollview_observer: ^1.24.0
  # 省市区选择
  flutter_pickers: ^2.1.9

#  flutter_boost:
#    git:
#      url: 'git@github.com:alibaba/flutter_boost.git'
#      ref: '4.2.1'

  flutter_slidable: ^3.0.1
  flutter_easyloading: ^3.0.5

  encrypt: ^5.0.0
  crypto: ^3.0.0

#  flutter_local_notifications: ^5.0.0+4
  url_launcher: ^6.0.4

  flutter_spinkit: ^5.2.0

  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

  mime: ^1.0.3

#  flutter_hooks: ^
#  flutter_linkify: ^
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0


  permission_handler: ^12.0.1
  #设备信息
  device_info_plus: ^11.3.0
  share: ^2.0.1
  path_provider: ^2.1.4
  provider: ^6.0.1
  rxdart: ^0.28.0

  shared_preferences: ^2.0.7
  #获取appName、packageName、version、buildNumber
  package_info_plus: ^9.0.0
  get: ^4.6.6
  get_storage: ^2.1.1

#  cached_network_image: ^2.5.1
  hive: ^2.0.4

  http_proxy: ^1.2.1

  dio: ^5.1.0
  dio_cookie_manager: ^3.1.1
  dio_cache_interceptor: ^4.0.5

  workmanager: ^0.7.0

  popover: ^0.3.0

#  pull_to_refresh: ^1.6.5
  easy_refresh: ^3.3.1
  custom_refresh_indicator: ^4.0.1
  visibility_detector: ^0.4.0+2

  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  web_socket_channel: ^3.0.3

  font_awesome_flutter: ^10.7.0
  timelines_plus: ^1.0.8

  enhance_stepper: ^1.0.1
  enhance_expansion_panel: ^0.7.0

  custom_timer: ^0.2.3
  scribble: ^0.10.0+1
  shimmer: ^3.0.0

  flutter_swiper_null_safety: ^1.0.2
  flutter_smart_dialog: ^4.2.1
  flutter_rating_bar: ^4.0.0
  desktop_drop: ^0.7.0
  badges: ^3.1.2
  svgaplayer_flutter: ^2.0.0
#  flutter_svg: ^1.1.6
  sliver_tools: ^0.2.12
  color_converter: ^0.2.1
  horizontal_data_table: ^4.1.4

  # 虚线边框
  dash_painter: ^1.0.2

  # 相机
  image_picker: ^1.0.0
  # 图片合并
  #  merge_images: ^1.0.3
  # 图片
  extended_image: ^9.1.0
  photo_manager: ^3.2.1
  # 图片预览
  photo_view: ^0.15.0
  # 图片压缩
  flutter_image_compress: ^2.0.3
  # 图片裁剪
  image_cropper: ^10.0.0+1
  # 图片保存
  image_gallery_saver_plus: ^4.0.1
  # 图片选择
  wechat_camera_picker: ^4.1.2
  wechat_assets_picker: ^9.0.4
#  wechat_assets_picker:
#    git:
#      url: 'git@github.com:shang1219178163/flutter_wechat_assets_picker.git'
#      ref: 'v8.6.2-change'

  # 文件选择
  file_picker: ^10.3.7
  # 文档预览
  file_preview: ^1.1.8
  open_file: ^3.3.2
  # 文件分享
  share_plus: ^12.0.1

  # 录音 + 播放音频的 SDK 工具库
  flutter_sound: ^9.2.13
  # 环境音频策略统一、后台管理
  audio_session: ^0.1.6
  # 简单播放一两段音效、短音频
  audioplayers: ^6.4.0
  # 音乐播放器（流畅、缓存、精控、后台、锁屏控制）
  just_audio: ^0.10.5

  # 视频播放
  video_player: ^2.2.3
  # 视频播放
  chewie: ^1.9.1
  # 视频压缩
  video_compress: ^3.1.2

  flutter_screen_wake: ^1.0.2
  volume_controller: ^3.4.0
  pip: ^0.0.3

  #微信登录+支付+分享
  fluwx: ^5.7.5
  # 苹果登录
  sign_in_with_apple: ^7.0.1

  azlistview: ^2.0.0
  common_utils: ^2.0.0
  lpinyin: ^2.0.0
  github_language_colors:
    git:
      url: git@github.com:Sky24n/github_language_colors.git

  # 签名
  signature: ^5.3.0

  #震动
  vibration: ^3.1.4

  json_to_dart:
    git:
      url: 'git@github.com:shang1219178163/json_to_dart.git'
      ref: 'v1.0.7.6'
#      version: ">=1.0.1"

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # 含 LruMap
  quiver: ^3.2.1

  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_translation: ^0.13.0
  google_mlkit_language_id: ^0.13.0

#  ffmpeg_kit_flutter_full: ^5.1.0


  expressions: ^0.2.5+2

  # 语音阅读
  flutter_tts: ^4.2.3
  pubspec_parse: ^1.4.0

  route_stack_manager: ^1.1.1

  flutter_markdown: ^0.7.4+3

  animations: ^2.0.9
  tab_container: ^3.5.3
  curved_navigation_bar: ^1.0.6
  rotated_corner_decoration: ^2.1.0+1

  appinio_swiper: ^2.1.1
  flutter_email_sender: ^8.0.0

  animated_toggle_switch: ^0.8.5

  flutter_pdfview: ^1.4.3

  record: ^6.1.2
  audio_visualizer:
    git:
      url: 'git@github.com:shang1219178163/audio_visualizer.git'
      ref: 'develop'



#  User:
#    hosted:
#      name: syn_mine_pages
#      url: git@github.com:shang1219178163/UserPlugin.git
#    version: 0.0.1

#  User: ^0.0.1
#    git:
#      url: 'git@github.com:shang1219178163/UserPlugin.git'
#      ref: 'master'

dependency_overrides:
#  intl: 0.17.0
  http: 1.0.0
  meta: ^1.12.0
  scrollable_positioned_list: ^0.3.8
  fluttertoast: ^9.0.0

  url_launcher_ios: 6.3.2
  # https://github.com/hnvn/flutter_image_cropper/issues/594  Error: The method 'toARGB32' isn't defined for the class 'Color'.
  image_cropper_platform_interface: 7.1.0
  image_cropper: 9.0.0

  # 修复 SUPPRESS_ERROR_PAGE https://github.com/pichillilorenzo/flutter_inappwebview/issues/2150
  webview_flutter_android: 3.16.1

  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

# User:
#   path: ../User

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  args: ^2.4.2
  # 通过dart进行调用shll命令执行
  process_run:
  color_logger: ^1.0.2


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/
    - assets/translations/
    - assets/data/
    - assets/images/
    - assets/images/curve/
    - assets/media/
    - lib/pages/demo/


flutter_assets_generator:
  assets_path: assets/
  path_ignore:
    - lib/
    - assets/media